const characters={lucien:{name:'Adrián',title:'El príncipe perfecto',age:25,desc:'Elegante, exigente y reservado.',tone:'sereno'},dante:{name:'Dante',title:'El rebelde',age:24,desc:'Sarcástico, impulsivo y ferozmente honesto.',tone:'provocador'},elias:{name:'Elías',title:'El genio distante',age:26,desc:'Analítico, observador y difícil de impresionar.',tone:'preciso'},nico:{name:'Nicolás',title:'El amigo encantador',age:23,desc:'Cálido, divertido y más profundo de lo que aparenta.',tone:'cálido'}};
const state={playerName:'',affinity:{lucien:0,dante:0,elias:0,nico:0},flags:{},scene:'intro'};
const $=id=>document.getElementById(id); const clamp=n=>Math.max(-100,Math.min(100,n));
function effect(e={}){Object.entries(e).forEach(([k,v])=>{if(state.affinity[k]!==undefined)state.affinity[k]=clamp(state.affinity[k]+v)});}
function flags(f=[]){f.forEach(x=>state.flags[x]=true)}
function renderRelationships(){const names={lucien:'Adrián',dante:'Dante',elias:'Elías',nico:'Nicolás'}; $('relationship-list').innerHTML=Object.entries(state.affinity).map(([id,v])=>`<div class="relationship-item"><div class="relationship-head"><span>${names[id]}</span><span>${v>25?'Cercanía':v<-25?'Tensión':'Intriga'}</span></div><div class="bar"><div class="bar-fill" style="width:${(v+100)/2}%"></div></div></div>`).join('')}
const scenes={
intro:{title:'La invitación',music:'Música: Piano de cristal con cuerdas suaves, como una puerta que acaba de abrirse.',speaker:'Narración',text:'La carta llegó sin remitente. Solo decía que tu nombre había sido elegido para una residencia creativa en Casa Aurora, un lugar donde cuatro jóvenes talentos adultos trabajan en un proyecto que nadie se atreve a explicar del todo.',next:'arrival'},
arrival:{title:'Casa Aurora',music:'Música: Vals lento con piano y campanillas, elegante pero ligeramente misterioso.',speaker:'Narración',text:'Cuando cruzas el jardín, cuatro miradas se encuentran contigo casi al mismo tiempo. La primera impresión no podría ser más distinta.',choices:[
{text:'Saludar con formalidad y observar antes de hablar.',effects:{lucien:5,elias:3},next:'lucien'},
{text:'Sonreír y hacer un comentario espontáneo sobre el lugar.',effects:{dante:4,nico:5},next:'nico'},
{text:'Preguntar directamente por qué te eligieron.',effects:{elias:6,dante:2},next:'elias'},
{text:'“Supongo que ustedes también recibieron una carta misteriosa.”',effects:{lucien:2,dante:5,nico:4},next:'dante'}]},
lucien:{title:'Una bienvenida impecable',music:'Música: Piano clásico con violines discretos, pulcro y refinado.',speaker:'Adrián',text:'“Adrián. Encantado. Espero que la residencia esté a la altura de lo que prometieron. ¿Te gustaría que te mostrara el salón principal?”',choices:[
{text:'“Sí, pero no hace falta que todo sea tan perfecto.”',effects:{lucien:-2},flags:['challenged_lucien'],next:'library'},
{text:'“Gracias. Me vendrá bien conocer el lugar.”',effects:{lucien:5},next:'library'},
{text:'“Prefiero explorar por mi cuenta.”',effects:{lucien:-4},next:'library'}]},
dante:{title:'Una primera provocación',music:'Música: Guitarra acústica y percusión ligera, con energía juguetona.',speaker:'Dante',text:'“Así que tú eres la nueva. Tranquila: nadie aquí sabe exactamente qué está haciendo. Algunos simplemente fingen mejor.”',choices:[
{text:'“Entonces tú debes ser excelente fingiendo.”',effects:{dante:5},next:'library'},
{text:'“Prefiero comprobarlo antes de creerlo.”',effects:{dante:2,elias:2},next:'library'},
{text:'“No me interesan los juegos.”',effects:{dante:-5},flags:['cold_to_dante'],next:'library'}]},
elias:{title:'Una observación inesperada',music:'Música: Piano minimalista con notas aisladas y un fondo ambiental tenue.',speaker:'Elías',text:'“Llegaste siete minutos antes. Eso significa que eres puntual o que no querías arriesgarte. Todavía no sé cuál de las dos.”',choices:[
{text:'“¿Siempre analizas a la gente así?”',effects:{elias:5},next:'library'},
{text:'“¿Y tú siempre dices en voz alta lo que piensas?”',effects:{elias:4,dante:2},next:'library'},
{text:'“Qué manera tan rara de presentarte.”',effects:{elias:-3},next:'library'}]},
nico:{title:'Una sonrisa familiar',music:'Música: Piano cálido y pizzicato de cuerdas, luminoso y acogedor.',speaker:'Nicolás',text:'“¡Por fin! Ven, te guardé el mejor lugar del salón. Si sobrevives a la primera reunión, te invito a conocer el jardín.”',choices:[
{text:'“Acepto. Pero si el lugar es terrible, será culpa tuya.”',effects:{nico:5},next:'library'},
{text:'“Gracias. Aunque quizá debería conocer primero a los demás.”',effects:{nico:2,elias:2},next:'library'},
{text:'“No necesito que me cuides.”',effects:{nico:-4},next:'library'}]},
library:{title:'La primera elección',music:'Música: Arpa suave y piano nocturno; la casa parece escuchar cada palabra.',speaker:'Narración',text:'Esa noche, el grupo se reúne en la biblioteca. Sobre la mesa hay cuatro carpetas y una pregunta: “¿Qué significa confiar en alguien?”. La respuesta puede cambiar la forma en que te ven.',choices:[
{text:'“Confiar es aceptar que no puedes controlarlo todo.”',effects:{lucien:5,elias:4},next:'night'},
{text:'“Confiar es saber que alguien seguirá ahí incluso después de una discusión.”',effects:{dante:5,nico:5},next:'night'},
{text:'“Confiar no es necesario. Lo importante es tener pruebas.”',effects:{elias:5,lucien:2,dante:-2},next:'night'},
{text:'“No lo sé todavía. Supongo que tendré que descubrirlo.”',effects:{nico:4,dante:3},next:'night'}]},
night:{title:'Bajo las estrellas',music:'Música: Piano nostálgico en tono menor con cuerdas suaves de fondo.',speaker:'Narración',text:'Más tarde, encuentras a los cuatro separados por el jardín. Por primera vez, nadie parece estar actuando para los demás. Cada uno te ofrece una conversación distinta.',choices:[
{text:'Quedarte con Adrián y preguntarle qué teme perder.',effects:{lucien:9},next:'route'},
{text:'Quedarte con Dante y pedirle una respuesta sincera.',effects:{dante:9},next:'route'},
{text:'Quedarte con Elías y preguntarle qué no puede explicar.',effects:{elias:9},next:'route'},
{text:'Quedarte con Nicolás y hablar de algo completamente cotidiano.',effects:{nico:9},next:'route'}]},
};
const routes={lucien:{music:'Música: Piano romántico y cuerdas de cámara, contenido y elegante.',best:{title:'La imperfección que elegiste',text:'Adrián deja de medir cada palabra. A tu lado descubre que una vida valiosa no necesita estar perfectamente ordenada. La relación nace de una decisión sencilla: dejarse conocer sin máscaras.',art:'lucien'},mid:{title:'Una promesa sin prisa',text:'No hay una respuesta definitiva, pero sí una puerta abierta. Adrián te pide que regreses a Casa Aurora y continúen descubriéndose, esta vez sin expectativas imposibles.',art:'lucien'}},dante:{music:'Música: Guitarra suave con batería ligera y un estribillo instrumental esperanzador.',best:{title:'Sin armadura',text:'Dante aprende que ser sincero no significa estar siempre a la defensiva. Entre bromas y conversaciones honestas, ambos encuentran una forma de acompañarse sin intentar cambiarse.',art:'dante'},mid:{title:'El desafío continúa',text:'Todavía quedan cosas que decir. Dante sonríe y te promete que la próxima conversación será más honesta que la anterior. Por ahora, eso basta.',art:'dante'}},elias:{music:'Música: Piano minimalista que lentamente incorpora violines cálidos.',best:{title:'Más allá de la lógica',text:'Elías admite que algunas decisiones no caben en una fórmula. Contigo aprende a expresar lo que siente antes de convertirlo en una conclusión. Es un comienzo tranquilo y sincero.',art:'elias'},mid:{title:'Una incógnita interesante',text:'Elías no sabe qué ocurrirá después, pero ya no necesita saberlo todo. Te propone seguir hablando, una conversación a la vez.',art:'elias'}},nico:{music:'Música: Piano cálido, cuerdas ligeras y una melodía luminosa de cierre.',best:{title:'Elegir quedarse',text:'Nicolás deja de esconder sus sentimientos detrás de una sonrisa. Descubre que ser el amigo de alguien no impide querer construir algo más, siempre que ambos lo decidan con honestidad.',art:'nico'},mid:{title:'Una amistad que florece',text:'La cercanía entre ustedes se vuelve más profunda. Quizá algún día cambie de nombre, pero por ahora ambos disfrutan de haber encontrado un lugar seguro en el otro.',art:'nico'}}};
function pickRoute(){const entries=Object.entries(state.affinity).sort((a,b)=>b[1]-a[1]);const [id,val]=entries[0];return val<15?null:id}
function art(id){const palettes={lucien:['#ead5df','#6f5264'],dante:['#e4d4cb','#584b54'],elias:['#d8dfea','#46576b'],nico:['#e8dccd','#6b5a47']};const [bg,fg]=palettes[id];return `<svg viewBox="0 0 500 300" xmlns="http://www.w3.org/2000/svg"><rect width="500" height="300" fill="${bg}"/><circle cx="250" cy="92" r="42" fill="#f0c9ae"/><path d="M208 85q12-55 48-38 34-12 46 39-34-18-94-1z" fill="${fg}"/><path d="M170 275q8-103 80-108 72 5 80 108z" fill="${fg}"/><circle cx="238" cy="96" r="3" fill="#33283a"/><circle cx="262" cy="96" r="3" fill="#33283a"/><path d="M246 112q8 6 16 0" fill="none" stroke="#92516f" stroke-width="2"/><path d="M320 155q-60 45-119 82" fill="none" stroke="#c27b9b" stroke-width="10" stroke-linecap="round"/><path d="M180 235q55-30 135 0" fill="none" stroke="#fff" stroke-width="8" stroke-linecap="round"/><text x="250" y="282" text-anchor="middle" font-family="Georgia" font-size="15" fill="#fff">${characters[id].name} · ${state.playerName}</text></svg>`}
function showScene(id){state.scene=id;const s=scenes[id];$('music-label').textContent=s.music;$('scene-title').textContent=s.title;$('speaker').textContent=s.speaker;$('dialogue').textContent=s.text;$('character-badge').classList.add('hidden');$('continue-btn').classList.add('hidden');$('choices').innerHTML='';if(['lucien','dante','elias','nico'].includes(id)){const c=characters[id];$('speaker').textContent=c.name;$('character-badge').textContent=`${c.title} · ${c.age} años`;$('character-badge').classList.remove('hidden')}
if(s.choices){s.choices.forEach((c,i)=>{const b=document.createElement('button');b.className='choice-btn';b.textContent=c.text;b.onclick=()=>{effect(c.effects);flags(c.flags);renderRelationships();if(c.next==='route')showRoute();else showScene(c.next)};$('choices').appendChild(b)})}else{$('continue-btn').classList.remove('hidden');$('continue-btn').onclick=()=>showScene(s.next)}renderRelationships()}
function showRoute(){const id=pickRoute();if(!id){showEnding(null);return}const c=characters[id];const r=routes[id];const high=state.affinity[id]>=55;const data=high?r.best:r.mid;$('music-label').textContent=r.music;$('scene-title').textContent=`Ruta de ${c.name}`;$('speaker').textContent=c.name;$('dialogue').textContent=data.text;$('character-badge').textContent=`${c.title} · afinidad ${state.affinity[id]}`;$('character-badge').classList.remove('hidden');$('choices').innerHTML='';const b=document.createElement('button');b.className='choice-btn';b.textContent='Ver mi final →';b.onclick=()=>showEnding(id,high?'best':'mid');$('choices').appendChild(b)}
function showEnding(id,type){$('game-screen').classList.add('hidden');$('ending-screen').classList.remove('hidden');if(!id){$('ending-type').textContent='FINAL INDEPENDIENTE';$('ending-title').textContent='Tu historia apenas comienza';$('ending-text').textContent=`${state.playerName}, ninguna ruta alcanzó todavía el punto en que una relación pudiera definirse. Pero Casa Aurora aún guarda muchas historias. Cada decisión de una próxima partida puede cambiarlo todo.`;$('ending-art').innerHTML='<svg viewBox="0 0 500 300" xmlns="http://www.w3.org/2000/svg"><rect width="500" height="300" fill="#eee2e9"/><circle cx="250" cy="130" r="62" fill="#fff" opacity=".8"/><path d="M120 265q130-100 260 0" fill="#92516f"/><text x="250" y="160" text-anchor="middle" font-family="Georgia" font-size="24" fill="#92516f">CASA AURORA</text></svg>';$('ending-stats').textContent='4 rutas · decisiones con consecuencias';return}const d=routes[id][type];$('ending-type').textContent=type==='best'?'FINAL LUMINOSO':'FINAL ABIERTO';$('ending-title').textContent=d.title;$('ending-text').textContent=`${state.playerName}, ${d.text}`;$('ending-art').innerHTML=art(id);$('ending-stats').textContent=`Ruta: ${characters[id].name} · Afinidad final: ${state.affinity[id]}`}
function reset(){state.playerName='';Object.keys(state.affinity).forEach(k=>state.affinity[k]=0);state.flags={};$('ending-screen').classList.add('hidden');$('game-screen').classList.add('hidden');$('title-screen').classList.remove('hidden');$('player-name').value='';$('name-error').textContent=''}
$('start-btn').onclick=()=>{const n=$('player-name').value.trim();if(!n){$('name-error').textContent='Escribe un nombre para comenzar.';return}state.playerName=n;$('player-display').textContent=n;$('title-screen').classList.add('hidden');$('game-screen').classList.remove('hidden');showScene('intro')};$('restart-btn').onclick=reset;$('ending-restart').onclick=reset;
